### ISSUE TITLE
Doesn't work with multiple services on one container

### ISSUE THREAD

**Issue by dorianim** [jittering/traefik-kop#14]
Currently, there is a problem when configuring multiple routers on one container. 
For example:
```yaml
minio:
  image: quay.io/minio/minio
  volumes:
    - ./minio:/data
  ports:
    - 9000:9000
    - 9001:9001
  command:
    - server
    - /data
    - --console-address
    - ":9001"
  environment:
    MINIO_ROOT_USER: root
    MINIO_ROOT_PASSWORD: root
  labels:
    traefik.enable: true
    traefik.http.routers.s3.rule: "Host(`s3.example.com`)"
    traefik.http.routers.s3.entrypoints: webs
    traefik.http.services.s3.loadbalancer.server.port: 9000

    traefik.http.routers.minio.rule: "Host(`minio.example.com`)"
    traefik.http.routers.minio.entrypoints: webs
    traefik.http.services.minio.loadbalancer.server.port: 9001
```

It would be really nice to get this working, as it is a bit annoying to put the second one into a different config file :)

Regards,
Dorian

**Comment by hongkongkiwi** [comment]
Please could you fix this? I'm also keen on this feature :)

**Comment by chetan** [comment]
@dorianim @hongkongkiwi I just tested this locally and it appears to work without issue. See this [sample compose file](https://github.com/jittering/traefik-kop/blob/f009b84193aa725ae879e6c6c347b85841589480/testing/docker-compose.yml#L10-L31) where I just added an example of a service with multiple ports exposed.

Here's the output when I bring up that service:

```text
time="2022-09-10T14:36:00-04:00" level=info msg="refreshing traefik-kop configuration"
time="2022-09-10T14:36:00-04:00" level=warning msg="found more than one host-port binding for container '/testing-helloworld-1' (5555:5555, 5566:5566)" service=hello2@docker service-type=http
time="2022-09-10T14:36:00-04:00" level=info msg="publishing http://1.2.3.4:5566" service-type=http service=hello2@docker
time="2022-09-10T14:36:00-04:00" level=warning msg="found more than one host-port binding for container '/testing-helloworld-1' (5555:5555, 5566:5566)" service=hello1@docker service-type=http
time="2022-09-10T14:36:00-04:00" level=info msg="publishing http://1.2.3.4:5555" service=hello1@docker service-type=http
```

**Comment by dorianim** [comment]
Ok, nevermind, I just forgot do define the service name. It works like this:
```yaml
minio:
  image: quay.io/minio/minio
  volumes:
    - ./minio:/data
  ports:
    - 9000:9000
    - 9001:9001
  command:
    - server
    - /data
    - --console-address
    - ":9001"
  environment:
    MINIO_ROOT_USER: root
    MINIO_ROOT_PASSWORD: root
  labels:
    traefik.enable: true
    traefik.http.routers.s3.rule: "Host(`s3.example.com`)"
    traefik.http.routers.s3.entrypoints: webs
    traefik.http.routers.s3.service: s3
    traefik.http.services.s3.loadbalancer.server.port: 9000

    traefik.http.routers.minio.rule: "Host(`minio.example.com`)"
    traefik.http.routers.minio.entrypoints: webs
    traefik.http.routers.minio.service: minio
    traefik.http.services.minio.loadbalancer.server.port: 9001
```
