### ISSUE TITLE
setting port for tcp service does not work

### ISSUE THREAD

**Issue by dorianim** [jittering/traefik-kop#16]
Hey :)

I have this configuration

```yaml
version: "3"

services:
  gitea:
    image: gitea/gitea
    ports:
      - "20080:3000"
      - "20022:22"
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: "Host(`git.domain`)"
      traefik.http.routers.gitea.entrypoints: webs
      traefik.http.routers.gitea.service: gitea@redis
      traefik.http.services.gitea.loadbalancer.server.port: 20080

      traefik.tcp.routers.gitea-ssh.rule: "HostSNI(`*`)"
      traefik.tcp.routers.gitea-ssh.entrypoints: ssh
      traefik.tcp.routers.gitea-ssh.service: gitea-ssh@redis
      traefik.tcp.services.gitea-ssh.loadbalancer.server.port: 20022
```
The port of the `gitea-ssh` service is not detected correctly:
![image](https://user-images.githubusercontent.com/30153207/192780834-8cdebc36-a054-4529-bfa0-2db7ff933f30.png)

And this is the log:
```
traefik-kop-traefik-kop-1  | time="2022-09-28T12:37:14Z" level=warning msg="found more than one host-port binding for container '/gitea-gitea-1' (20022:22, 20080:3000)" service-type=tcp service=gitea-ssh@docker
```
