### ISSUE TITLE
Provide IP for each docker via label

### ISSUE THREAD

**Issue by Svenum** [jittering/traefik-kop#17]
It would be nice to add for each docker a own "bind_ip". Maybe via label. So that you can multiple IPs.
example:
``` yml
labels:
    kop.bind.ip: 10.10.10.16
    ...
```

If you don't have this feature you need a second reverse-proxy, or not?
