### ISSUE TITLE
Possibility to ignoring specific containers

### ISSUE THREAD

**Issue by SAOPP** [jittering/traefik-kop#36]
Hi there!

Is it possible to add a label to indicate the names of those containers that should not be monitored?

I encountered on one of my hosts the fact that there was already a kop there, and I needed to add several new services that had to be monitored by another (new) kop to another traefik, and it turns out that I can't ignore the old containers that work in conjunction with old kop instance, and the wrong entries still end up on my other traffic...

**Comment by chetan** [comment]
@SAOPP I'm not sure I understand your setup here. Are you trying to run two instances of `kop` on a single docker host, each pushing services to different redis+traefik instances?

**Comment by SAOPP** [comment]
Yep, due to some features, it now looks like this on this host.

**Comment by chetan** [comment]
Still not sure what you're looking for here. Please re-open and add more info if it's something you're still interested in.

**Comment by SAOPP** [comment]
Hi! I already forgot that I left such a request. :smile: 

I was talking about a flag that would contain the names of containers that should be ignored, for example:

`variable: "container_name_1, container_name_2"`

For what? To ignore the necessary containers, even if it's containers have traefik labels.

**Comment by chetan** [comment]
@SAOPP so you want to configure `traefik-kop` to ignore containers specified as a list in the variable? So something like:

```yaml
services:
  traefik-kop:
    image: "ghcr.io/jittering/traefik-kop:latest"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "REDIS_ADDR=192.168.1.50:6379"
      - "BIND_IP=192.168.1.75"
      - "IGNORE_CONTAINERS=container_name_1, container_name_2"
```
