### ISSUE TITLE
#Question - Docker Socket Proxy 🦄

### ISSUE THREAD

**Issue by TCS-UK** [jittering/traefik-kop#40]
Hiya,

Do you have any plans to add docker-socket-proxy compatibility so we can connect to the docker socket via TCP?

[Tecnativa Github](https://github.com/Tecnativa/docker-socket-proxy)

**Comment by chetan** [comment]
If the api is compatible with normal clients then I don't see why it wouldn't work out of the box. Have you tried it?

**Comment by TCS-UK** [comment]
Now I feel an idiot…no I haven’t. The read me sort of indicated that it only worked with the docker socket and nothing else. I’ll give it ago later and report back 👍

**Comment by chetan** [comment]
I've had problems with http in the past but it may work now. Just give it a shot and report back

**Comment by TCS-UK** [comment]
> I've had problems with http in the past but it may work now. Just give it a shot and report back

🤦‍♂️ IT WORKS 🤣

```
services:
  traefik-kop:
    image: "ghcr.io/jittering/traefik-kop:latest"
    container_name: traefik-ktop-redis
    security_opt:
      - no-new-privileges:true
    depends_on:
      - traefik-socket-proxy
    restart: unless-stopped

    environment:
      - "DOCKER_HOST=tcp://traefik-socket-proxy:2375"
      - "REDIS_ADDR=192.168.5.209:32768"
      - "BIND_IP=192.168.5.210"
      - "REDIS_PASS=REDACTED"

########################################################################################################

  traefik-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: traefik-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    expose:
      - 2375
    environment:
      LOG_LEVEL: info
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      

```
