### ISSUE TITLE
kop crashes on `GetOutboundIP` if all docker networks are `internal`

### ISSUE THREAD

**Issue by FoxxMD** [jittering/traefik-kop#51]
This was found by a user using one of my projects: https://github.com/FoxxMD/traefik-homelab/issues/1#issuecomment-2895032259

And can be reproduced with the following stack:

```yaml
services:
  traefik-kop-test:
    image: "ghcr.io/jittering/traefik-kop:latest"
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=redis:6379"
    depends_on:
      - redis
    networks:
      - kop_test
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: redis:7-alpine
    networks:
      - kop_test
      - default
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

networks:
  default:
    internal: true # destroy stack and then set to false before deploying to make kop work
  kop_test:
    internal: true
```

When **all networks** attached to the container are `internal` kop crashes after logging network unreachable

```
traefik-kop-test-1  | 2025-05-20T16:21:00.030794566Z time="2025-05-20T16:21:00Z" level=fatal msg="dial udp 8.8.8.8:80: connect: network is unreachable"
```

My guess is that `conn.LocalAddr()` does not exist because the route lookup done by go(?) could not find a gateway that could by used to resolve a path to [`8.8.8.8`](https://github.com/jittering/traefik-kop/blob/main/bin/traefik-kop/main.go#L175) due to all routing setup by docker having restricted paths due to `internal` networks.
