### ISSUE TITLE
TCP port cannot be found

### ISSUE THREAD

**Issue by Andorbal** [jittering/traefik-kop#52]
I'm having trouble routing a TCP port.  It seems like I'm having the same problem as [described here](https://github.com/jittering/traefik-kop/issues/16), but it's not working for me.  I'm using v0.16 and Traefik v3.4.1.  It looks like Traefik-kop is not using the explicitly defined port and instead trying to get the port from the docker compose file, of which there are more than a few!

My logs look like this:
```
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="found tcp service: gitlab-ssh@docker" service-type=tcp service=gitlab-ssh@docker
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="found router 'gitlab-ssh@docker' for service gitlab-ssh"
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="found container '/gitlab' (13033645f82892bb24c4fdfbdc549fe3ccef32fc088b3483bdf0bfc1b1d0ed4f) for service 'gitlab-ssh'"
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="no network label set for gitlab-ssh@docker"
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="found router 'gitlab-ssh@docker' for service gitlab-ssh"
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="found container '/gitlab' (13033645f82892bb24c4fdfbdc549fe3ccef32fc088b3483bdf0bfc1b1d0ed4f) for service 'gitlab-ssh'"
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=warning msg="found more than one host-port binding for container '/gitlab' (122:22, 5000:5000, 5005:5005, 5050:5050, 80:80)" service=gitlab-ssh@docker service-type=tcp
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="using existing port " service=gitlab-ssh@docker service-type=tcp
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=debug msg="using ip '10.0.0.10' and port '' for gitlab-ssh@docker" service-type=tcp service=gitlab-ssh@docker
traefik-kop-1  | time="2025-06-09T02:52:25Z" level=info msg="publishing 10.0.0.10" service=gitlab-ssh@docker service-type=tcp
```

This is my docker compose file, which does not work.

```
services:
  gitlab:
    image: gitlab/gitlab-ce:17.4.2-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['db_password'] = '${DB_PASSWORD}'
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
    ports:
      - '80:80'
      - '122:22'
      - '5000:5000'
      - '5005:5005'
      - '5050:5050'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - './config/gitlab.rb:/etc/gitlab/gitlab.rb'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    labels:
      # Web server
      - traefik.enable=true
      - traefik.http.routers.gitlab-web.entrypoints=websecure
      - traefik.http.routers.gitlab-web.rule=Host("gitlab.example.com")
      - traefik.http.routers.gitlab-web.service=gitlab-web
      - traefik.http.services.gitlab-web.loadbalancer.server.port=80
      # Registry server
      - traefik.http.routers.gitlab-registry.entrypoints=websecure
      - traefik.http.routers.gitlab-registry.rule=Host("registry.example.com")
      - traefik.http.routers.gitlab-registry.service=gitlab-registry
      - traefik.http.services.gitlab-registry.loadbalancer.server.port=5005
      # SSH host for git repository access
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI("*")
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh-gitlab
      - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh
      - traefik.tcp.services.gitlab-ssh.loadBalancer.server.port=22
```

If I remove the labels from the above file and then add a config file to Traefik that looks like this, the routing works correctly.

```
#traefik:
enabled: true
http:
  routers:
    gitlab-web:
      rule: Host("gitlab.example.com")
      entrypoints: websecure
      service: gitlab-web
    gitlab-registry:
      rule: Host("registry.example.com")
      entrypoints: websecure
      service: gitlab-registry
  services:
    gitlab-web:
      loadBalancer:
        servers:
          - url: http://10.0.0.10
    gitlab-registry:
      loadBalancer:
        servers:
          - url: "http://10.0.0.10:5005"
tcp:
  routers:
    gitlab-ssh:
      rule: HostSNI("*")
      entrypoints: ssh-gitlab
      service: gitlab-ssh
  services:
    gitlab-ssh:
      loadBalancer:
        servers:
          - address: 10.0.0.10:122
            port: 122
```

Other than the `address` property, the configuration looks the same to me.  In both cases, the HTTP and HTTPS routing seems to work fine.

If it matters, my Traefik endpoints are configured like this:
```
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  ssh-gitlab:
    address: ":122"
```

I appreciate the help, and I think this is a great project!
